[libraries]
# Removed from build
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.26.0" }
archunit-junit5-api = { group = "com.tngtech.archunit", name = "archunit-junit5-api", version = "1.2.1" }

# Remove from build
camel-quarkus-jackson = { group = "org.apache.camel.quarkus", name = "camel-quarkus-jackson", version = "3.11.0" }

# Remove from build
commons-vfs2 = { group = "org.apache.commons", name = "commons-vfs2", version = "2.9.0" }
graal = { group = "org.graalvm.nativeimage", name = "svm", version = "23.1.2" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version = "1.5.5.Final" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version = "1.5.5.Final" }

# Removed from build, called mongockBom 
mongock-bom = { group = "com.github.cloudyrock.mongock", name = "mongock-bom", version = "4.3.8" }

# Removed from build, called resteasy_problem_version
quarkus-resteasy-problem = { group = "com.tietoevry.quarkus", name = "quarkus-resteasy-problem", version = "3.9.0" }

# Remove from build
wiremock = { group = "com.github.tomakehurst", name = "wiremock-jre8", version = "3.0.1" }

# Remove from build
testcontainers-keycloak = { group = "com.github.dasniko", name = "testcontainers-keycloak", version = "3.3.1" }

[plugins]
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version = "2.4.1" }
gradle-node = { id = "com.github.node-gradle.node", version = "7.0.2" }
liquibase = { id = "org.liquibase.gradle", version = "2.2.0" }
sonarqube = { id = "org.sonarqube", version = "4.3.0.3225" }
openapi-generator = { id = "org.openapi.generator", version = "4.2.3" }
checkstyle = { id = "org.checkstyle", version = "10.17.0" }
no-http-checkstyle = { id = "io.github.checkstyle.checkstyle", version = "0.0.11" }
modernizer = { id = "org.gaul.modernizer", version = "1.8.0" }